### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by masterofobzene** [stealthizer/jdownloader-proxy-generator#5]
```
C:\Users\PC>E:\Storage\PROGRAMAS\PORTABLES\jdownloader-proxy-generator-main\proxy-scrapper.py
Traceback (most recent call last):
  File "E:\Storage\PROGRAMAS\PORTABLES\jdownloader-proxy-generator-main\proxy-scrapper.py", line 75, in <module>
    proxy_list = proxy_list + get_proxies_from_proxyscan_io()
  File "E:\Storage\PROGRAMAS\PORTABLES\jdownloader-proxy-generator-main\proxy-scrapper.py", line 56, in get_proxies_from_proxyscan_io
    proxies = json.loads(res.text)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cooperdk** [comment]
Maybe that's because proxyscan.io has no proxies anymore. The site seems to be unmaintained, at any rate it has ZERO proxies.
